import { art, defineTheme, glyph } from "../define";

export const anastasia = defineTheme({
  id: "anastasia",
  identity: { name: "Codename: Anastasia", tagline: "A storybook, in gold leaf", description: "Ornamental storybook editorial: gold flourishes, an arched title and a board framed like an heirloom.", mood: "dark", kind: "comic" },
  colors: {
    background: "#141026",
    backgroundAlt: "#3a2a55",
    surface: "#1d1833",
    ink: "#f5ecd9",
    muted: "#c2b49b",
    accent: "#d4af6a",
    accentInk: "#1b1530",
    playerOne: "#efbfd1",
    playerTwo: "#a9cdee",
    board: "#2b2246",
    cell: "#1a1530",
    line: "#5a4a7a",
    highlight: "#d4af6a",
    winInk: "#1b1530",
  },
  typography: { display: "storybook", title: "ornament", subtitle: "italic" },
  surfaces: { card: "ornate", button: "outline", texture: "linen", radius: 10 },
  players: { layout: "flank", card: "portrait" },
  board: { style: "soft", frame: "ornament", cellRadius: 8, cellBorder: 1 },
  symbols: { suggested: [glyph("star"), glyph("heart")], treatment: "emboss" },
  artwork: {
    imageBlend: { blend: "soft-light", overlayOpacity: 0.2, frame: "glow" },
    pieces: [
      art("arch", "Ornate arch", "arch", "behind-board", { size: 26, y: -4, tint: "accent", opacity: 0.35, mobile: "keep" }),
      art("corner", "Flourish", "ornament-corner", "page-left", { size: 9, tint: "accent", opacity: 0.8, mobile: "hide" }),
      art("sparkle", "Gold dust", "sparkles", "title-right", { size: 5, x: 1, tint: "accent" }),
    ],
  },
  background: { slot: 38, recipe: "radial-top" },
  effects: { sparkles: true },
  reactions: { style: "editorial", flourish: "sparkle" },
  chapters: { style: "title-card" },
  chat: { bubble: "round", sticker: "circle" },
  motion: { personality: "calm" },
  sound: { profile: "chime" },
  specialMoments: { narration: "banner" },
  collage: { accents: ["ornament-corner", "sparkles", "wax-seal", "tape"] },
});
