import { art, defineTheme, glyph } from "../define";

export const rosesChampagne = defineTheme({
  id: "roses-champagne",
  identity: { name: "Roses and Champagne", tagline: "A toast, in gold", description: "Luxury editorial: champagne paper, gold double rules, a rose and a coupe raised.", mood: "light", kind: "comic" },
  colors: {
    background: "#f6eee3",
    backgroundAlt: "#ecd9c4",
    surface: "#fffaf3",
    ink: "#3a2328",
    muted: "#6e5156",
    accent: "#8a5e34",
    accentInk: "#ffffff",
    playerOne: "#b03a55",
    playerTwo: "#7a5a24",
    board: "#e6d2bb",
    cell: "#fffdf9",
    line: "#c9a77f",
    highlight: "#f1dcb4",
    winInk: "#3a2328",
  },
  typography: { display: "editorial", title: "ornament", subtitle: "caps" },
  surfaces: { card: "paper", button: "pill", texture: "paper", radius: 6 },
  players: { layout: "stack", card: "polaroid" },
  board: { style: "soft", frame: "double", cellRadius: 6, cellBorder: 1 },
  symbols: { suggested: [glyph("rose"), glyph("star")], treatment: "emboss" },
  artwork: {
    imageBlend: { blend: "multiply", overlayOpacity: 0.1, frame: "polaroid" },
    pieces: [
      art("coupe", "Champagne coupe", "coupe", "page-left", { size: 9, rotate: -6, tint: "accent", mobile: "hide" }),
      art("rose", "Rose stem", "rose-stem", "board-bottom-right", { size: 7, rotate: 18, x: 2.5, y: 1, tint: "p1", layer: "front" }),
      art("gold", "Gold sparkle", "sparkles", "title-right", { size: 5, x: 1, tint: "accent" }),
    ],
  },
  background: { slot: 34, recipe: "radial-top" },
  effects: { sparkles: true },
  reactions: { style: "editorial", flourish: "confetti" },
  chapters: { style: "title-card" },
  chat: { bubble: "round", sticker: "polaroid" },
  motion: { personality: "calm" },
  sound: { profile: "chime" },
  specialMoments: { narration: "banner" },
  collage: { accents: ["rose", "coupe", "sparkles", "tape"] },
});
