import { art, defineTheme, glyph } from "../define";

export const space = defineTheme({
  id: "space",
  identity: { name: "Space", tagline: "Floating in starlight", description: "Deep nebula, slow planets and a board that floats in its own glow.", mood: "dark" },
  colors: {
    background: "#070818",
    backgroundAlt: "#1d1446",
    surface: "#11132c",
    ink: "#eef0ff",
    muted: "#a8add8",
    accent: "#f3c969",
    accentInk: "#151028",
    playerOne: "#ffd36e",
    playerTwo: "#a7b9ff",
    board: "#2a2f66",
    cell: "#12152f",
    line: "#3d4384",
    highlight: "#f3c969",
    winInk: "#151028",
  },
  typography: { display: "modern", title: "spaced-caps", subtitle: "caps" },
  surfaces: { card: "glass", button: "glass", texture: "grain", radius: 22 },
  players: { layout: "flank", card: "minimal" },
  board: { style: "glass", frame: "float", cellRadius: 18, cellBorder: 1 },
  symbols: { suggested: [glyph("moon"), glyph("star")], treatment: "glow" },
  artwork: {
    imageBlend: { blend: "screen", overlayOpacity: 0.25, frame: "glow" },
    pieces: [
      art("planet", "Ringed planet", "planet", "page-right", { size: 14, rotate: -14, tint: "p2", opacity: 0.9, mobile: "hide" }),
      art("moon", "Moon", "crescent", "title-left", { size: 5, rotate: -20, x: -0.5, tint: "p1" }),
      art("stars", "Constellation", "constellation", "board-top-right", { size: 9, x: 2.5, y: -3, tint: "ink", opacity: 0.6 }),
    ],
  },
  background: { slot: 32, recipe: "radial-top" },
  effects: { stars: true, nebula: true, shootingStars: true },
  reactions: { style: "cinematic", flourish: "starburst" },
  chapters: { style: "curtain" },
  chat: { bubble: "glass", sticker: "circle" },
  motion: { personality: "floaty" },
  sound: { profile: "chime" },
  specialMoments: { narration: "subtitle" },
  collage: { mode: "off", accents: ["sparkles"] },
});
