/** Built-in original placeholder artwork. Drawn in SVG by components/themes/Motifs.tsx. */
export const MOTIFS = [
  ["pearl-strand", "Pearl strand"],
  ["pearl-cluster", "Pearls & shell"],
  ["moon", "Full moon"],
  ["crescent", "Crescent moon"],
  ["constellation", "Constellation"],
  ["planet", "Ringed planet"],
  ["sparkles", "Sparkles"],
  ["rose", "Rose bloom"],
  ["rose-stem", "Rose stem"],
  ["blossom-branch", "Blossom branch"],
  ["petals", "Petals"],
  ["hamster-peek", "Peeking hamster"],
  ["seeds", "Sunflower seeds"],
  ["waves", "Tide lines"],
  ["horizon-sun", "Horizon sun"],
  ["pebbles", "Pebbles"],
  ["coupe", "Champagne coupe"],
  ["brush-stroke", "Brush stroke"],
  ["palette", "Paint palette"],
  ["paint-dabs", "Paint dabs"],
  ["ornament-corner", "Ornamental corner"],
  ["arch", "Ornate arch"],
  ["diagram", "Diagram doodle"],
  ["sticky-note", "Sticky note"],
  ["paperclip", "Paperclip"],
  ["speed-lines", "Speed lines"],
  ["panels", "Panel frames"],
  ["screentone", "Screentone"],
  ["hearts", "Heart doodles"],
  ["ribbon", "Ribbon"],
  ["border-line", "Border line"],
  ["torn-strip", "Torn paper strip"],
  ["window", "Window frame"],
  ["bulb", "Hanging bulb"],
  ["tag", "Graffiti tag"],
  ["sticker", "Star sticker"],
  ["poster", "Poster fragment"],
  ["tape", "Tape"],
  ["wax-seal", "Wax seal"],
  ["thorns", "Thorn line"],
  ["burst", "Comic burst"],
  ["number", "Chapter number"],
] as const;

export type MotifId = (typeof MOTIFS)[number][0];
export const MOTIF_IDS: readonly MotifId[] = MOTIFS.map(([id]) => id);
export const MOTIF_LABELS = Object.fromEntries(MOTIFS) as Record<MotifId, string>;
